const RULES = {
  CHANCES: 6,
};

const ACTIONS = {
  MAKE_GUESS: 'MAKE_GUESS',
  MAKE_RIGHT_GUESS: 'MAKE_RIGHT_GUESS',
  MAKE_WRONG_GUESS: 'MAKE_WONG_GUESS',
  GET_NEW_WORD: 'GET_NEW_WORD',
  TRIGGER_WIN: 'TRIGGER_WIN',
  TRIGGER_LOSE: 'TRIGGER_LOSE',
};

const WORDS = [
  'APPLE',
  'ORANGE',
  'BIKE',
  'CAR',
];

const CANVAS = {
  WIDTH: 500,
  HEIGHT: 450,
  CTX_WIDTH: 250,
  CTX_HEIGHT: 225,
  STROKE_COLOR: '#000000',
};

CANVAS.GALLOW = {
  LEFT: 80,
  BOTTOM: CANVAS.CTX_HEIGHT - 40,
  WIDTH: 100,
  HEIGHT: 150,
  ROPE_LENGTH: 20,
};

CANVAS.HEAD = {
  TOP: (CANVAS.GALLOW.BOTTOM - CANVAS.GALLOW.HEIGHT) + CANVAS.GALLOW.ROPE_LENGTH,
  LEFT: CANVAS.GALLOW.LEFT + CANVAS.GALLOW.WIDTH,
  WIDTH: 18,
};

CANVAS.BODY = {
  TOP: CANVAS.HEAD.TOP + (CANVAS.HEAD.WIDTH * 2),
  LEFT: CANVAS.HEAD.LEFT,
  HEIGHT: 80,
};

CANVAS.LEFT_ARM = {
  TOP: CANVAS.BODY.TOP + 10,
  LEFT: CANVAS.BODY.LEFT,
  WIDTH: 30,
};

CANVAS.RIGHT_ARM = {
  TOP: CANVAS.LEFT_ARM.TOP,
  LEFT: CANVAS.BODY.LEFT,
  WIDTH: 30,
};

CANVAS.LEFT_LEG = {
  TOP: CANVAS.BODY.TOP + CANVAS.BODY.HEIGHT,
  LEFT: CANVAS.BODY.LEFT,
  WIDTH: 30,
};

CANVAS.RIGHT_LEG = {
  TOP: CANVAS.BODY.TOP + CANVAS.BODY.HEIGHT,
  LEFT: CANVAS.BODY.LEFT,
  WIDTH: 30,
};

export default null;
export {
  RULES,
  ACTIONS,
  WORDS,
  CANVAS,
};
